# Generated by Django 4.0.6 on 2022-07-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_date_added_merchpost_date_posted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MerchPost',
        ),
    ]
